name: My S3 Build

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: |
        python -m pip install setuptools --upgrade pip
        pip install --upgrade platformio

    - name: Run PlatformIO
      run: pio run -d src -e opendtufusion-de

    - name: Rename Firmware
      run: python scripts/getVersion.py opendtufusion-de >> $GITHUB_OUTPUT

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: opendtufusion-de
        path: firmware/*
